backend/apps/posts/urls.py
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page 
from posts.views import *


app_name = 'posts'
urlpatterns = [
    # path('', cache_page(60)(MusHome.as_view()), name='home'),
    path('', MusHome.as_view(), name='home'),
    path('about/',  about, name='about'),
    path('addpage/', AddPage.as_view(), name='add_page'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('post/<slug:post_slug>/', show_post, name='post'),
    path('category/<slug:cat_slug>/', MusCategory.as_view(), name='category'),
    path('api/v1/musician/', MusicianViewList.as_view()),
    path('api/v1/musician/<int:pk>/', MusicianDetail.as_view()),
    
    
]

backend/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include, re_path
from apps.posts.urls import urlpatterns as ur
from config import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.posts.urls')),
    path('captcha/',include('captcha.urls')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include("debug_toolbar.urls")),] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

backend/apps/posts/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

class Musician(models.Model):
    title = models.CharField(max_length = 255, verbose_name = 'Заголовок')
    slug = models.SlugField(max_length = 255, unique = True, db_index = True, verbose_name = 'URL')
    content = models.TextField(blank = False, verbose_name = 'Текст статьи')
    photo = models.ImageField(upload_to = 'photos/%Y/%m/%d/', verbose_name = 'Фото') 
    time_create = models.DateTimeField(auto_now_add = True, verbose_name = 'Дата создания')
    time_update = models.DateTimeField(auto_now = True, verbose_name = 'Дата обновления')
    is_published = models.BooleanField(default = True, verbose_name = 'Опубликовано')
    cat = models.ForeignKey('Category', on_delete = models.PROTECT, verbose_name = 'Жанр')
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:post', kwargs = {'post_slug':self.slug})
    
    class Meta:
        verbose_name = 'Музыкант'
        verbose_name_plural = 'Музыканты'
        ordering = ['-time_create']

class Category(models.Model):
    name = models.CharField(max_length = 100, db_index = True, verbose_name = 'Жанр')
    slug = models.SlugField(max_length = 255, unique = True, db_index = True, verbose_name = 'URL')
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('posts:category', kwargs = {'cat_slug':self.slug})
   
    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ['name']

class Comment(models.Model):
    post = models.ForeignKey(Musician, on_delete=models.CASCADE, verbose_name = 'Пост')
    content = models.TextField(blank = False, verbose_name = 'Текст комментария')
    time_create = models.DateTimeField(auto_now_add = True, verbose_name = 'Дата создания')
    time_update = models.DateTimeField(auto_now = True, verbose_name = 'Дата обновления')
    is_published = models.BooleanField(default = True, verbose_name = 'Опубликовано')
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.PROTECT)
    
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-time_create']

backend/apps/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from posts.models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from captcha.fields import CaptchaField
 
class AddPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категория не выбрана" 

    class Meta:
        model = Musician
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')
        return title  
    # title = forms.CharField(max_length = 255, label = 'Заголовок', widget = forms.TextInput(attrs = {'class': 'form-input'}))
    # slug = forms.SlugField(max_length = 255, label = 'URL')
    # content = forms.CharField(widget = forms.Textarea(attrs={'cols': 60, 'rows': 10}), label = 'Текст статьи')
    # is_published = forms.BooleanField(label = 'Опубликовано', required = False, initial = True)
    # cat = forms.ModelChoiceField(queryset = Category.objects.all(), label = 'Жанр', empty_label = 'Категория не выбрана')

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput (attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Почта', widget=forms.TextInput (attrs={'class': 'form-input'})) 
    password1 = forms.CharField(label='Пароль', widget=forms.TextInput (attrs={'class': 'form-input'})) 
    password2 = forms.CharField(label='Повтор пароля', widget=forms.TextInput (attrs={'class': 'form-input'}))
    captcha = CaptchaField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput (attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput (attrs={'class': 'form-input'})) 

class ContactForm(forms.Form):

    name = forms.CharField(label='Имя', max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))
    captcha = CaptchaField()

class AddCommForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['cat'].empty_label = "Пост не выбран" 

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }
   

backend/apps/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound, Http404
from posts.models import Musician, Category
from posts.forms import *
from posts.utils import *
from django.views.generic import ListView, DetailView, CreateView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout, login
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.paginator import Paginator
from posts.serializers import MusicianSerializer
from rest_framework import generics
from rest_framework.permissions import *

class IsOwnerORAdminORReadonly(BasePermission):
    """
    A base class from which all permission classes should inherit.
    """
    def has_object_permission(self, request, view, obj):
        """
        Return `True` if permission is granted, `False` otherwise.
        """
        if request.method in SAFE_METHODS or request.user.is_staff:
            return True
        return obj.user==request.user

class MusicianViewList(generics.ListCreateAPIView):
    queryset = Musician.objects.all()
    serializer_class = MusicianSerializer
    permission_classes = (IsAuthenticatedOrReadOnly,)

class MusicianDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Musician.objects.all()
    serializer_class = MusicianSerializer
    permission_classes = (IsOwnerORAdminORReadonly,)


class MusHome(DataMixin, ListView): 
    model = Musician
    template_name = 'posts/index.html'
    context_object_name = 'posts'

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Главная страница") 
        context = dict(list(context.items()) + list(c_def.items())) 
        return context
    
    def get_queryset(self):
        return Musician.objects.filter(is_published = True).select_related('cat')
    
# def index(request):
#     posts = Musician.objects.all()
#     context = {
#         'posts': posts,  
#         'title': 'Главная страница',
#         'cat_selected': 0,
#     }
#     return render(request, 'posts/index.html', context = context)

# @login_required
def about(request):
    contact_list = Musician.objects.all()
    
    
    # paginator = Paginator(contact_list, 1)
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
    if not request.user.is_authenticated:
        context = {   
        'title': 'О сайте',
        'cat_selected': 0,
        'menu':[menu[0],menu[2]],
        # 'page_obj':page_obj
        }
    else:
        context = {   
            'title': 'О сайте',
            'cat_selected': 0,
            'menu':menu,
            # 'page_obj':page_obj
        }
    return render(request, 'posts/about.html', context = context)

class AddPage(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddPostForm
    template_name = 'posts/addpage.html'
    success_url = reverse_lazy('posts:home')
    login_url = reverse_lazy('posts:login')
    # raise_exception = True
    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавление статьи') 
        context = dict(list(context.items()) + list(c_def.items()))  
        return context
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(AddPage, self).form_valid(form)
# @login_required
# def add_page(request):
    
#     if request.method == 'POST':
#         form = AddPostForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.cleaned_data['user']=request.user
#             # form.save()
#             Musician.objects.create(**form.cleaned_data)
#             return redirect('posts:home')

#     else:    
#         form = AddPostForm() 
    
#     context = {
#         'form':form,
#         'title':'Добавление статьи',
#         'menu':menu
#     }
#     return render(request, 'posts/addpage.html', context = context)

class ContactFormView(DataMixin, FormView):
    form_class = ContactForm
    template_name = 'posts/contact.html'
    success_url = reverse_lazy('posts:home') 

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Обратная связь') 
        context = dict(list(context.items()) + list(c_def.items()))  
        return context

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('posts:home')

# class ShowPost(DataMixin,DetailView):
#     model = Musician
#     template_name = 'posts/post.html'
#     slug_url_kwarg = 'post_slug'
#     context_object_name = 'post'

#     def get_context_data(self, *, object_list = None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         c_def = self.get_user_context(title=context['post'].title, cat_selected = context['post'].cat_id) 
#         context = dict(list(context.items()) + list(c_def.items())) 
#         return context
    

def show_post(request, post_slug):
    post = get_object_or_404(Musician, slug = post_slug)
    comments = Comment.objects.filter(post=post)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = AddCommForm(request.POST, request.FILES)
            if form.is_valid():
                form.cleaned_data['post']=post
                form.cleaned_data['is_published']=True
                form.cleaned_data['user']=request.user
                # form.save()
                Comment.objects.create(**form.cleaned_data)
                return redirect('posts:home')

        else:    
            form = AddCommForm() 
        context ={
            'form':form,
            'post':post,
            'title':post.title,
            'cat_selected':post.cat_id,
            'menu':menu,
            'comments':comments,
        }
    else:
        context ={
            'post':post,
            'title':post.title,
            'cat_selected':post.cat_id,
            'menu':[menu[0],menu[2]],
            'comments':comments,
        }
    return render(request, 'posts/post.html', context = context)

class MusCategory(DataMixin, ListView):
    
    model = Musician
    template_name = 'posts/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        c = Category.objects.get(slug = self.kwargs['cat_slug'])
        c_def = self.get_user_context(title='Категория - ' + c.name, cat_selected = c.id) 
        context = dict(list(context.items()) + list(c_def.items())) 

        return context

    def get_queryset(self):
        return Musician.objects.filter(cat__slug = self.kwargs['cat_slug'], is_published = True).select_related('cat')
        

def show_category(request, cat_slug):
    cat_id = Category.objects.get(slug = cat_slug).id
    posts = Musician.objects.filter(cat_id = cat_id)

    if len(posts)==0:
        raise Http404()
    context = {
        'posts': posts,  
        'title': 'Отображение по категориям',
        'cat_selected': cat_id,
        'menu':menu,
    }
    return render(request, 'posts/index.html', context = context)

def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

# def login(request):
#     return HttpResponse('Авторизация')

class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'posts/register.html'
    success_url = reverse_lazy('posts:login') 
    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация') 
        context = dict(list(context.items()) + list(c_def.items()))  
        return context

    def form_valid(self, form):
        """
        Вызывается при успешной регистрации и авторизует пользователя
        """
        user = form.save()
        login(self.request, user)
        return redirect('posts:home')

class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'posts/login.html'
    

    def get_context_data(self, *, object_list = None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title = 'Авторизация')
        context = dict(list(context.items()) + list(c_def.items()))
        return context
    def get_success_url(self):
        return reverse_lazy('posts:home')

def logout_user(request):
    logout(request)
    return redirect('posts:login')

backend/apps/posts/templates/posts/about.html
{% extends 'layout/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Сайт, содержащий статьи об известных музыкантах</p>
{% endblock %}

backend/apps/posts/templates/posts/addpage.html
{% extends 'layout/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="{% url 'posts:add_page' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}  
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Добавить</button> 
</form>
{% endblock %}

backend/apps/posts/templates/posts/contact.html
{% extends 'layout/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form method="post">
    {% csrf_token %}  
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Добавить</button> 
</form>
{% endblock %}

backend/apps/posts/templates/posts/index.html
{% extends 'layout/base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}

			<li><div class="article-panel">
				<p class="first">Категория: {{p.cat}}</p> 
				<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
			</div>
			{% if p.photo %}
			<p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
			{% endif %}

			<h2>{{p.title}}</h2>
			{% autoescape on %} 
			{{p.content|linebreaks|truncatewords:50}}
			{% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
			</li>
	{% endfor %} 
</ul>
{% endblock %}

backend/apps/posts/templates/posts/list_categories.html
{% for c in cats %}
{% if c.pk == cat_selected %}
<li class="selected">{{c.name}}</li>
{% else %}
<li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
{% endif %}
{% endfor %}

backend/apps/posts/templates/posts/login.html
{% extends 'layout/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Войти</button>
</form>
{% endblock %}

backend/apps/posts/templates/posts/main_menu.html
{% for m in menu %}
{% if not forloop.last %}
<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% else %}
<li class="last"><a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endif %}
{% endfor %}

backend/apps/posts/templates/posts/post.html
{% extends 'layout/base.html' %}

{% block content %}
<h1>{{post.title}}</h1>
{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{post.content|linebreaks}}
{% if request.user.is_authenticated %}
<h1>Оставить комментарий</h1>
<form method="post">
    {% csrf_token %}  
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Добавить</button> 
</form>
{% endif %}
<h1>Комментарии</h1>
{% for com in comments %}
<ul>
    <li>{{com.user}} {{com.time_create}}</li>
    <p>{{com.content}}</p>
</ul>
{% endfor %}
{% endblock %}

backend/apps/posts/templates/posts/register.html
{% extends 'layout/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Регистрация</button>
</form>
{% endblock %}